
name: "Brandon T. Willard"
markdown: rdiscount
author: "Brandon T. Willard"
#url: http://brandonwillard.github.io

navigations:
  - title: About
    class: fa fa-user
    href: /blog/about.html
  - title: Blog
    class: fa fa-quote-left
    href: /blog/index.html
  - title: Publications
    class: fa fa-book
    href: /blog/publications.html
  - title: Projects
    class: fa fa-file-code-o
    href: /blog/projects.html

